# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mblazev/Hacking/thesis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mblazev/Hacking/thesis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mblazev/Hacking/thesis/CMakeFiles /home/mblazev/Hacking/thesis/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mblazev/Hacking/thesis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dagmatch_greedy

# Build rule for target.
dagmatch_greedy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dagmatch_greedy
.PHONY : dagmatch_greedy

# fast build rule for target.
dagmatch_greedy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_greedy.dir/build.make CMakeFiles/dagmatch_greedy.dir/build
.PHONY : dagmatch_greedy/fast

#=============================================================================
# Target rules for targets named dagmatch_fpt

# Build rule for target.
dagmatch_fpt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dagmatch_fpt
.PHONY : dagmatch_fpt

# fast build rule for target.
dagmatch_fpt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_fpt.dir/build.make CMakeFiles/dagmatch_fpt.dir/build
.PHONY : dagmatch_fpt/fast

#=============================================================================
# Target rules for targets named dagmatch_lp

# Build rule for target.
dagmatch_lp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dagmatch_lp
.PHONY : dagmatch_lp

# fast build rule for target.
dagmatch_lp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/build
.PHONY : dagmatch_lp/fast

geno/augmentedLagrangian.o: geno/augmentedLagrangian.cpp.o

.PHONY : geno/augmentedLagrangian.o

# target to build an object file
geno/augmentedLagrangian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/geno/augmentedLagrangian.cpp.o
.PHONY : geno/augmentedLagrangian.cpp.o

geno/augmentedLagrangian.i: geno/augmentedLagrangian.cpp.i

.PHONY : geno/augmentedLagrangian.i

# target to preprocess a source file
geno/augmentedLagrangian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/geno/augmentedLagrangian.cpp.i
.PHONY : geno/augmentedLagrangian.cpp.i

geno/augmentedLagrangian.s: geno/augmentedLagrangian.cpp.s

.PHONY : geno/augmentedLagrangian.s

# target to generate assembly for a file
geno/augmentedLagrangian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/geno/augmentedLagrangian.cpp.s
.PHONY : geno/augmentedLagrangian.cpp.s

geno/lbfgsb.o: geno/lbfgsb.cpp.o

.PHONY : geno/lbfgsb.o

# target to build an object file
geno/lbfgsb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/geno/lbfgsb.cpp.o
.PHONY : geno/lbfgsb.cpp.o

geno/lbfgsb.i: geno/lbfgsb.cpp.i

.PHONY : geno/lbfgsb.i

# target to preprocess a source file
geno/lbfgsb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/geno/lbfgsb.cpp.i
.PHONY : geno/lbfgsb.cpp.i

geno/lbfgsb.s: geno/lbfgsb.cpp.s

.PHONY : geno/lbfgsb.s

# target to generate assembly for a file
geno/lbfgsb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/geno/lbfgsb.cpp.s
.PHONY : geno/lbfgsb.cpp.s

geno/lineSearch.o: geno/lineSearch.cpp.o

.PHONY : geno/lineSearch.o

# target to build an object file
geno/lineSearch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/geno/lineSearch.cpp.o
.PHONY : geno/lineSearch.cpp.o

geno/lineSearch.i: geno/lineSearch.cpp.i

.PHONY : geno/lineSearch.i

# target to preprocess a source file
geno/lineSearch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/geno/lineSearch.cpp.i
.PHONY : geno/lineSearch.cpp.i

geno/lineSearch.s: geno/lineSearch.cpp.s

.PHONY : geno/lineSearch.s

# target to generate assembly for a file
geno/lineSearch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/geno/lineSearch.cpp.s
.PHONY : geno/lineSearch.cpp.s

src/AntichainConstraint.o: src/AntichainConstraint.cpp.o

.PHONY : src/AntichainConstraint.o

# target to build an object file
src/AntichainConstraint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/AntichainConstraint.cpp.o
.PHONY : src/AntichainConstraint.cpp.o

src/AntichainConstraint.i: src/AntichainConstraint.cpp.i

.PHONY : src/AntichainConstraint.i

# target to preprocess a source file
src/AntichainConstraint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/AntichainConstraint.cpp.i
.PHONY : src/AntichainConstraint.cpp.i

src/AntichainConstraint.s: src/AntichainConstraint.cpp.s

.PHONY : src/AntichainConstraint.s

# target to generate assembly for a file
src/AntichainConstraint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/AntichainConstraint.cpp.s
.PHONY : src/AntichainConstraint.cpp.s

src/Constraint.o: src/Constraint.cpp.o

.PHONY : src/Constraint.o

# target to build an object file
src/Constraint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/Constraint.cpp.o
.PHONY : src/Constraint.cpp.o

src/Constraint.i: src/Constraint.cpp.i

.PHONY : src/Constraint.i

# target to preprocess a source file
src/Constraint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/Constraint.cpp.i
.PHONY : src/Constraint.cpp.i

src/Constraint.s: src/Constraint.cpp.s

.PHONY : src/Constraint.s

# target to generate assembly for a file
src/Constraint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/Constraint.cpp.s
.PHONY : src/Constraint.cpp.s

src/CrossingConstraint.o: src/CrossingConstraint.cpp.o

.PHONY : src/CrossingConstraint.o

# target to build an object file
src/CrossingConstraint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/CrossingConstraint.cpp.o
.PHONY : src/CrossingConstraint.cpp.o

src/CrossingConstraint.i: src/CrossingConstraint.cpp.i

.PHONY : src/CrossingConstraint.i

# target to preprocess a source file
src/CrossingConstraint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/CrossingConstraint.cpp.i
.PHONY : src/CrossingConstraint.cpp.i

src/CrossingConstraint.s: src/CrossingConstraint.cpp.s

.PHONY : src/CrossingConstraint.s

# target to generate assembly for a file
src/CrossingConstraint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/CrossingConstraint.cpp.s
.PHONY : src/CrossingConstraint.cpp.s

src/Graph.o: src/Graph.cpp.o

.PHONY : src/Graph.o

# target to build an object file
src/Graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/Graph.cpp.o
.PHONY : src/Graph.cpp.o

src/Graph.i: src/Graph.cpp.i

.PHONY : src/Graph.i

# target to preprocess a source file
src/Graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/Graph.cpp.i
.PHONY : src/Graph.cpp.i

src/Graph.s: src/Graph.cpp.s

.PHONY : src/Graph.s

# target to generate assembly for a file
src/Graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/Graph.cpp.s
.PHONY : src/Graph.cpp.s

src/IndependentSetConstraint.o: src/IndependentSetConstraint.cpp.o

.PHONY : src/IndependentSetConstraint.o

# target to build an object file
src/IndependentSetConstraint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/IndependentSetConstraint.cpp.o
.PHONY : src/IndependentSetConstraint.cpp.o

src/IndependentSetConstraint.i: src/IndependentSetConstraint.cpp.i

.PHONY : src/IndependentSetConstraint.i

# target to preprocess a source file
src/IndependentSetConstraint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/IndependentSetConstraint.cpp.i
.PHONY : src/IndependentSetConstraint.cpp.i

src/IndependentSetConstraint.s: src/IndependentSetConstraint.cpp.s

.PHONY : src/IndependentSetConstraint.s

# target to generate assembly for a file
src/IndependentSetConstraint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/IndependentSetConstraint.cpp.s
.PHONY : src/IndependentSetConstraint.cpp.s

src/LP.o: src/LP.cpp.o

.PHONY : src/LP.o

# target to build an object file
src/LP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/LP.cpp.o
.PHONY : src/LP.cpp.o

src/LP.i: src/LP.cpp.i

.PHONY : src/LP.i

# target to preprocess a source file
src/LP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/LP.cpp.i
.PHONY : src/LP.cpp.i

src/LP.s: src/LP.cpp.s

.PHONY : src/LP.s

# target to generate assembly for a file
src/LP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/LP.cpp.s
.PHONY : src/LP.cpp.s

src/LPFInt.o: src/LPFInt.cpp.o

.PHONY : src/LPFInt.o

# target to build an object file
src/LPFInt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/LPFInt.cpp.o
.PHONY : src/LPFInt.cpp.o

src/LPFInt.i: src/LPFInt.cpp.i

.PHONY : src/LPFInt.i

# target to preprocess a source file
src/LPFInt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/LPFInt.cpp.i
.PHONY : src/LPFInt.cpp.i

src/LPFInt.s: src/LPFInt.cpp.s

.PHONY : src/LPFInt.s

# target to generate assembly for a file
src/LPFInt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/LPFInt.cpp.s
.PHONY : src/LPFInt.cpp.s

src/LPInt.o: src/LPInt.cpp.o

.PHONY : src/LPInt.o

# target to build an object file
src/LPInt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/LPInt.cpp.o
.PHONY : src/LPInt.cpp.o

src/LPInt.i: src/LPInt.cpp.i

.PHONY : src/LPInt.i

# target to preprocess a source file
src/LPInt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/LPInt.cpp.i
.PHONY : src/LPInt.cpp.i

src/LPInt.s: src/LPInt.cpp.s

.PHONY : src/LPInt.s

# target to generate assembly for a file
src/LPInt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/LPInt.cpp.s
.PHONY : src/LPInt.cpp.s

src/greedy.o: src/greedy.cpp.o

.PHONY : src/greedy.o

# target to build an object file
src/greedy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_greedy.dir/build.make CMakeFiles/dagmatch_greedy.dir/src/greedy.cpp.o
.PHONY : src/greedy.cpp.o

src/greedy.i: src/greedy.cpp.i

.PHONY : src/greedy.i

# target to preprocess a source file
src/greedy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_greedy.dir/build.make CMakeFiles/dagmatch_greedy.dir/src/greedy.cpp.i
.PHONY : src/greedy.cpp.i

src/greedy.s: src/greedy.cpp.s

.PHONY : src/greedy.s

# target to generate assembly for a file
src/greedy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_greedy.dir/build.make CMakeFiles/dagmatch_greedy.dir/src/greedy.cpp.s
.PHONY : src/greedy.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/match.o: src/match.cpp.o

.PHONY : src/match.o

# target to build an object file
src/match.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_fpt.dir/build.make CMakeFiles/dagmatch_fpt.dir/src/match.cpp.o
.PHONY : src/match.cpp.o

src/match.i: src/match.cpp.i

.PHONY : src/match.i

# target to preprocess a source file
src/match.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_fpt.dir/build.make CMakeFiles/dagmatch_fpt.dir/src/match.cpp.i
.PHONY : src/match.cpp.i

src/match.s: src/match.cpp.s

.PHONY : src/match.s

# target to generate assembly for a file
src/match.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_fpt.dir/build.make CMakeFiles/dagmatch_fpt.dir/src/match.cpp.s
.PHONY : src/match.cpp.s

src/read_csv.o: src/read_csv.cpp.o

.PHONY : src/read_csv.o

# target to build an object file
src/read_csv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_greedy.dir/build.make CMakeFiles/dagmatch_greedy.dir/src/read_csv.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_fpt.dir/build.make CMakeFiles/dagmatch_fpt.dir/src/read_csv.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/read_csv.cpp.o
.PHONY : src/read_csv.cpp.o

src/read_csv.i: src/read_csv.cpp.i

.PHONY : src/read_csv.i

# target to preprocess a source file
src/read_csv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_greedy.dir/build.make CMakeFiles/dagmatch_greedy.dir/src/read_csv.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_fpt.dir/build.make CMakeFiles/dagmatch_fpt.dir/src/read_csv.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/read_csv.cpp.i
.PHONY : src/read_csv.cpp.i

src/read_csv.s: src/read_csv.cpp.s

.PHONY : src/read_csv.s

# target to generate assembly for a file
src/read_csv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_greedy.dir/build.make CMakeFiles/dagmatch_greedy.dir/src/read_csv.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_fpt.dir/build.make CMakeFiles/dagmatch_fpt.dir/src/read_csv.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dagmatch_lp.dir/build.make CMakeFiles/dagmatch_lp.dir/src/read_csv.cpp.s
.PHONY : src/read_csv.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dagmatch_fpt"
	@echo "... dagmatch_greedy"
	@echo "... dagmatch_lp"
	@echo "... geno/augmentedLagrangian.o"
	@echo "... geno/augmentedLagrangian.i"
	@echo "... geno/augmentedLagrangian.s"
	@echo "... geno/lbfgsb.o"
	@echo "... geno/lbfgsb.i"
	@echo "... geno/lbfgsb.s"
	@echo "... geno/lineSearch.o"
	@echo "... geno/lineSearch.i"
	@echo "... geno/lineSearch.s"
	@echo "... src/AntichainConstraint.o"
	@echo "... src/AntichainConstraint.i"
	@echo "... src/AntichainConstraint.s"
	@echo "... src/Constraint.o"
	@echo "... src/Constraint.i"
	@echo "... src/Constraint.s"
	@echo "... src/CrossingConstraint.o"
	@echo "... src/CrossingConstraint.i"
	@echo "... src/CrossingConstraint.s"
	@echo "... src/Graph.o"
	@echo "... src/Graph.i"
	@echo "... src/Graph.s"
	@echo "... src/IndependentSetConstraint.o"
	@echo "... src/IndependentSetConstraint.i"
	@echo "... src/IndependentSetConstraint.s"
	@echo "... src/LP.o"
	@echo "... src/LP.i"
	@echo "... src/LP.s"
	@echo "... src/LPFInt.o"
	@echo "... src/LPFInt.i"
	@echo "... src/LPFInt.s"
	@echo "... src/LPInt.o"
	@echo "... src/LPInt.i"
	@echo "... src/LPInt.s"
	@echo "... src/greedy.o"
	@echo "... src/greedy.i"
	@echo "... src/greedy.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/match.o"
	@echo "... src/match.i"
	@echo "... src/match.s"
	@echo "... src/read_csv.o"
	@echo "... src/read_csv.i"
	@echo "... src/read_csv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

